;              
CREATE USER IF NOT EXISTS SA SALT '04bc01dd03ab26ba' HASH '5779df09914b38a013417a72b17970d29f5da48b40c337dc00cb0601579b8e07' ADMIN;            
CREATE MEMORY TABLE PUBLIC.COVER(
    ID UUID NOT NULL,
    HEIGHT INTEGER,
    URL VARCHAR(255),
    WIDTH INTEGER
);         
ALTER TABLE PUBLIC.COVER ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID);   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COVER;    
CREATE MEMORY TABLE PUBLIC.ITEM(
    ID UUID NOT NULL,
    CREATION_DATE TIMESTAMP,
    DESCRIPTION LONGTEXT SELECTIVITY 100,
    DOWNLOAD_DATE TIMESTAMP,
    FILE_NAME VARCHAR(255),
    LENGTH BIGINT,
    MIME_TYPE VARCHAR(255),
    PUB_DATE TIMESTAMP,
    STATUS VARCHAR(255),
    TITLE VARCHAR(255),
    URL VARCHAR(65535),
    COVER_ID UUID,
    PODCAST_ID UUID
);    
ALTER TABLE PUBLIC.ITEM ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ITEM;     
CREATE MEMORY TABLE PUBLIC.PODCAST(
    ID UUID NOT NULL,
    DESCRIPTION LONGTEXT SELECTIVITY 100,
    HAS_TO_BE_DELETED BOOLEAN,
    LAST_UPDATE TIMESTAMP,
    SIGNATURE VARCHAR(255),
    TITLE VARCHAR(255),
    TYPE VARCHAR(255),
    URL VARCHAR(65535),
    COVER_ID UUID
);    
ALTER TABLE PUBLIC.PODCAST ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PODCAST;  
CREATE MEMORY TABLE PUBLIC.PODCAST_TAGS(
    PODCASTS_ID UUID NOT NULL,
    TAGS_ID UUID NOT NULL
);           
ALTER TABLE PUBLIC.PODCAST_TAGS ADD CONSTRAINT PUBLIC.CONSTRAINT_27 PRIMARY KEY(PODCASTS_ID, TAGS_ID);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PODCAST_TAGS;             
CREATE MEMORY TABLE PUBLIC.TAG(
    ID UUID NOT NULL,
    NAME VARCHAR(255)
); 
ALTER TABLE PUBLIC.TAG ADD CONSTRAINT PUBLIC.CONSTRAINT_14 PRIMARY KEY(ID);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TAG;      
CREATE MEMORY TABLE PUBLIC.WATCH_LIST(
    ID UUID NOT NULL,
    NAME VARCHAR(255)
);          
ALTER TABLE PUBLIC.WATCH_LIST ADD CONSTRAINT PUBLIC.CONSTRAINT_18 PRIMARY KEY(ID);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.WATCH_LIST;               
CREATE MEMORY TABLE PUBLIC.WATCH_LIST_ITEMS(
    WATCH_LISTS_ID UUID NOT NULL,
    ITEMS_ID UUID NOT NULL
);   
ALTER TABLE PUBLIC.WATCH_LIST_ITEMS ADD CONSTRAINT PUBLIC.CONSTRAINT_E PRIMARY KEY(WATCH_LISTS_ID, ITEMS_ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.WATCH_LIST_ITEMS;         
ALTER TABLE PUBLIC.TAG ADD CONSTRAINT PUBLIC.UK_1WDPSED5KNA2Y38HNBGRNHI5B UNIQUE(NAME);        
ALTER TABLE PUBLIC.WATCH_LIST_ITEMS ADD CONSTRAINT PUBLIC.FK_D53PIU62OTQLR2SM3LPYH8RDF FOREIGN KEY(WATCH_LISTS_ID) REFERENCES PUBLIC.WATCH_LIST(ID) NOCHECK;   
ALTER TABLE PUBLIC.PODCAST ADD CONSTRAINT PUBLIC.FK_ALCK7HBRTPW1G3K2JC9W216M0 FOREIGN KEY(COVER_ID) REFERENCES PUBLIC.COVER(ID) NOCHECK;       
ALTER TABLE PUBLIC.PODCAST_TAGS ADD CONSTRAINT PUBLIC.FK_OJ2A2JLPQRSC1ACU4RTPOVQ8E FOREIGN KEY(PODCASTS_ID) REFERENCES PUBLIC.PODCAST(ID) NOCHECK;             
ALTER TABLE PUBLIC.ITEM ADD CONSTRAINT PUBLIC.FK_JUPRTIVKJ6T8VUV3TQDRK0ONU FOREIGN KEY(COVER_ID) REFERENCES PUBLIC.COVER(ID) NOCHECK;          
ALTER TABLE PUBLIC.PODCAST_TAGS ADD CONSTRAINT PUBLIC.FK_3O1SV9QVO2VCB0C5BME0DJ9P3 FOREIGN KEY(TAGS_ID) REFERENCES PUBLIC.TAG(ID) NOCHECK;     
ALTER TABLE PUBLIC.ITEM ADD CONSTRAINT PUBLIC.FK_PMSDRYDB6TT158XTQ8CDIGM0N FOREIGN KEY(PODCAST_ID) REFERENCES PUBLIC.PODCAST(ID) NOCHECK;      
ALTER TABLE PUBLIC.WATCH_LIST_ITEMS ADD CONSTRAINT PUBLIC.FK_TKCOSNNJIL1DF7FFD4QL6FMDC FOREIGN KEY(ITEMS_ID) REFERENCES PUBLIC.ITEM(ID) NOCHECK;               
